"""change for inventory

Revision ID: 62c314d756e6
Revises: 01807c169da0
Create Date: 2026-03-06 09:25:26.636691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c314d756e6'
down_revision: Union[str, Sequence[str], None] = '01807c169da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('uom', sa.String(length=10), nullable=False),
    sa.Column('min_stock', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_stock',
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_on_hand', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id')
    )
    op.create_table('menu_ingredient',
    sa.Column('menu_item_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_required', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('menu_item', 'base_price',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('menu_item_variant', 'price_delta',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('order_item', 'unit_price',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('payment', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('order_item', 'unit_price',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('menu_item_variant', 'price_delta',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('menu_item', 'base_price',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_table('stock_movements')
    op.drop_table('menu_ingredient')
    op.drop_table('ingredient_stock')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
